[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ab_utils"
version= "0.0.2"
description = "Alex's utility functions for genomic data science"
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "pandas-checks",
    "statannotations",
]
readme = "README.md"

[tool.hatch.build.targets.wheel]
include = ["ab_utils/**"]

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
snakemake-minimal = "<=9.16"

[tool.pixi.pypi-dependencies]
ab_utils = { path = ".", editable = true }

[tool.pixi.tasks]
test_smk = "snakemake --cores 4 test"
test_log = "python3 test/test_log.py"
test = [{task = 'test_smk'}, {task = 'test_log'}]
